#!/usr/bin/env ruby
#
# Transforms the existing mirror
#

require 'fileutils'
require 'json'
require 'rubygems/package'
require 'yaml'

gems = []

Dir[File.expand_path('../mirror/gems/*.gem', __FILE__)].sort.each do |gem_path|
  gem_name = File.basename(gem_path, '.gem')
  gem_spec = Gem::Package.new(gem_path).spec rescue nil
  unless gem_spec
    # ignore broken gems
    next
  end

  nix_path =
    "gems/#{gem_spec.name[0]}/#{gem_spec.name}/#{gem_spec.version}.json"
  if File.exist? nix_path
    gems << gem_name
    next
  end

  gem_hash = `nix-hash --base32 --type sha256 "#{gem_path}"`.strip

  nix = {
    sha256: gem_hash,

    meta: {
      description: gem_spec.description,
      homepage: gem_spec.homepage,
      license: gem_spec.license,
    }
  }

  FileUtils.mkdir_p File.dirname(nix_path)
  File.write(nix_path, JSON.pretty_generate(nix))

  puts gem_name
end
